dubbo:
  application:
    name: b2c-search-service
  registry:
    address: zookeeper://192.168.56.88:2181
  protocol:
    name: dubbo
    port: 20883
spring:
  datasource:
    druid:
      #JDBC四要素
      url: jdbc:mysql://192.168.56.88:3306/b2c?serverTimezone=GMT%2B8&characterEncoding=utf-8
      #用户名
      username: root
      #加密后的密码
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

      #数据源配置
      #初始化连接数
      initial-size: 1
      #最大连接数量
      max-active: 20
      #获取连接时最大等待时间
      max-wait: 10000
      #最小连接数量
      min-idle: 1
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #用来检测连接是否有效的SQL，解决数据库断开连接的问题
      validation-query: select 1

      #StatViewServlet配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

      #WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #排除一些不必要的url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.88:9300 #连接接口9300 访问接口9200
  redis:
    host: 192.168.56.88
    port: 6379
  rabbitmq:
    host: 192.168.56.88
    port: 5672
    username: admin
    password: 123

mybatis:
  #类型别名扫描的包
  type-aliases-package: com.turing.b2c.model.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #懒加载相关
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #最好加上该设置，否则mybatis默认情况下equals,clone,hashCode,toString都会触发懒加载
    #该属性是个Set集合，需要使用“-”来逐一添加一项或多项配置（数组、List类似）
    lazy-load-trigger-methods:
    - ""
    #映射骆驼命名法
    map-underscore-to-camel-case: true


#在运行时输出SQL执行日志（MyBatis默认为INFO级别，看不到）
logging:
  level:
    com.turing.b2c.mapper: debug
